# Generated by Django 4.1.7 on 2023-03-02 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Finch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(max_length=100)),
                ('true_finch', models.BooleanField()),
                ('description', models.TextField(max_length=250)),
                ('length', models.IntegerField()),
                ('wingspan', models.IntegerField()),
            ],
        ),
    ]
