# Generated by Django 4.1.7 on 2023-03-02 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finch',
            name='picture',
            field=models.CharField(default='https://t3.ftcdn.net/jpg/03/47/29/10/360_F_347291083_bgz19M5P0YAlDmWXs7EnvU3AJutsEmmf.jpg', max_length=500),
            preserve_default=False,
        ),
    ]
